//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events.Data.EventsManDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipantEvent()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Notifications = new HashSet<Notification>();
            this.PrivateInvites = new HashSet<PrivateInvite>();
        }
    
        public string id { get; set; }
        public string attend { get; set; }
        public string Eventid { get; set; }
        public string Participantid { get; set; }
        public string PreferredFoodid { get; set; }
    
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual PreferredFood PreferredFood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivateInvite> PrivateInvites { get; set; }
    }
}
