//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.ParticipantEvents = new HashSet<ParticipantEvent>();
            this.Speakers = new HashSet<Speaker>();
            this.Sponsors = new HashSet<Sponsor>();
            this.Comments = new HashSet<Comment>();
            this.IsPublic = true;
            this.StartDateTime = DateTime.Now;
        }
    
        public string Id { get; set; }
        public string objectId { get; set; }

        [Required]
        [MaxLength(200)]
        public string Title { get; set; }

        public string Description { get; set; }
        [Required]
        public DateTime StartDateTime { get; set; }

        public TimeSpan? Duration { get; set; }

        public DateTime? endTime { get; set; }
        public string AuthorId { get; set; }

        public virtual ApplicationUser Author { get; set; }

        [MaxLength(200)]
        public string Location { get; set; }

        public bool IsPublic { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
        public string Gpslocationid { get; set; }
        public string EventTypeid { get; set; }
        public string Addressid { get; set; }
        public string Adminid { get; set; }
        public string EventProgramid { get; set; }
        public string EventCatergoryid { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual Gpslocation Gpslocation { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual EventProgram EventProgram { get; set; }
        public virtual EventCatergory EventCatergory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantEvent> ParticipantEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Speaker> Speakers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sponsor> Sponsors { get; set; }
    }
}
