//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter
    {
        public string id { get; set; }
        public string updates { get; set; }
        public string Participantid { get; set; }
        public string NewsletterTypeid { get; set; }
    
        public virtual NewsletterType NewsletterType { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
